development:
  adapter: postgresql
  encoding: unicode
  database: petshop_development
  pool: 5
  username:
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: petshop_test
  pool: 5
  username:
  password:
  timeout: 5000
